export interface InnovationComment {
  brand: string;
  likes: number;
  text: string;
}

export interface InnovationOpportunity {
  id: string;
  title: string;
  category: "producto" | "estrategia" | "canal";
  signal: string;
  gap: string;
  opportunity: string;
  brands: [string, number | string][];
  evidence: number;
  fase3: number;
  comments: InnovationComment[];
}

export interface IdealItem {
  n: string;
  title: string;
  desc: string;
  src: string;
}

export interface BrandChartData {
  dimensions: string[];
  brands: string[];
  colors: string[];
  data: number[][];
}

export const dogOpportunities: InnovationOpportunity[] = [
  {id:"d-granel",title:"El comprador de granel sabe que es malo — pero no tiene alternativa",category:"producto",signal:"Los consumidores compran al granel en tiendas de barrio porque el empacado es inalcanzable. Saben que la calidad es inferior — reportan mal olor, textura rara — pero el precio del empacado los expulsa. Son consumidores conscientes atrapados por el precio.",gap:"No existe empaque económico que compita en precio con el granel sin sacrificar calidad. El consumidor elige entre caro-bueno o barato-malo.",opportunity:"SKU de formato accesible (1kg–2kg) con calidad garantizada y precio competitivo contra el granel. Capturar al consumidor que YA quiere algo mejor pero no puede pagarlo.",brands:[["Dog Chow",42],["Ringo",15],["Chunky",8]],evidence:65,fase3:7,comments:[{brand:"Dog Chow",likes:3,text:"Antes lo compraba a granel porq me salía más económico pero tenía este mismo problema del olor."},{brand:"Dog Chow",likes:1,text:"Yo le compro a granel pero me da miedo porque uno no sabe cómo almacenan eso en las tiendas."}]},
  {id:"d-olor",title:"El olor es el criterio de calidad #1 del consumidor — no los ingredientes",category:"producto",signal:"El consumidor no lee la tabla nutricional. Abre el bulto, huele, y decide si es bueno o malo. 'Mal olor' es la queja más frecuente y visceral en los comentarios. El granel huele peor, el empacado huele a harina. Ninguna marca huele a comida real.",gap:"Todas las marcas económicas huelen igual: a harina industrial. El consumidor asocia ese olor con baja calidad, y tiene razón. Ninguna marca ha trabajado el olor como atributo de producto.",opportunity:"Croqueta que huela a carne real al abrir el empaque. Ganar la prueba en tienda con el sentido que el consumidor sí usa. El olor diferencia antes de que el perro pruebe.",brands:[["Dog Chow",23],["Ringo",8],["Chunky",4]],evidence:35,fase3:5,comments:[{brand:"Dog Chow",likes:3,text:"Buenos días. El alimento está con muy mal olor, se siente cuando ya está puesto en el plato del perro."},{brand:"Dog Chow",likes:1,text:"Antes lo compraba a granel porq me salía más económico pero tenía este mismo problema del olor."}]},
  {id:"d-consistencia",title:"El consumidor no quiere mejor fórmula — quiere la misma fórmula",category:"producto",signal:"Cada vez que Dog Chow cambia su fórmula, textura o forma de croqueta, genera una oleada masiva de rechazo. El perro deja de comer y el dueño cambia de marca. El consumidor no pide innovación — pide que no le cambien lo que ya funciona.",gap:"Todas las marcas cambian fórmulas sin avisar. El consumidor lo descubre cuando el perro rechaza el alimento. No hay ninguna marca que garantice estabilidad de fórmula como promesa de producto.",opportunity:"Vender consistencia como feature: 'misma fórmula garantizada.' El claim más poderoso no es 'mejor ingrediente' sino 'si tu perro lo come hoy, lo va a comer mañana.' Ningún competidor puede hacer esa promesa porque todos ya cambiaron.",brands:[["Dog Chow",116],["Ringo",12],["Chunky",5]],evidence:133,fase3:9,comments:[{brand:"Dog Chow",likes:2,text:"Muy buenas, cambiaron la versión del alimento y mi perro de raza pequeña no quiere comer hace una semana, me siento en la obligación de comprarle Pro Plan."},{brand:"Dog Chow",likes:0,text:"Hola, mi perro solo come este alimento porque ninguno le gustó y le hacen daño. Ahora no quiere comer, el nuevo no le gustó y es de pepitas más grandes."}]},
  {id:"d-mezcla",title:"Los consumidores ya mezclan concentrado con comida casera — nadie diseña para eso",category:"producto",signal:"Los dueños mezclan concentrado con arroz, pollo, verduras, huevo. No es BARF puro ni concentrado puro — es un híbrido que el consumidor inventó solo. Todas las marcas compiten por ser 'alimento completo' pero el consumidor ya decidió que no le da solo concentrado.",gap:"Ninguna marca diseña su producto para ser mezclado. Las tablas de porciones asumen que el perro come SOLO concentrado. El consumidor mezcla sin guía y sin producto adaptado.",opportunity:"Producto diseñado como 'base nutricional' para complementar con comida casera. Porción menor, concentración mayor, guía de mezcla en empaque. Capturar la mitad del plato que hoy es arroz con pollo.",brands:[["Dog Chow",19],["Ringo",5],["Chunky",3]],evidence:27,fase3:14,comments:[{brand:"Dog Chow",likes:1,text:"Yo le mezclo el Dog Chow con arroz y pollo porque solo pepas no le gusta. Pero no sé si eso está bien."},{brand:"Usuario",likes:2,text:"Le doy concentrado en la mañana y en la noche le cocino pollo con verduras. El veterinario dice que está perfecto de peso."}]},
  {id:"d-croqueta",title:"Tamaño de croqueta inadecuado",category:"producto",signal:"Los dueños de razas pequeñas no pueden alimentar a sus perros con las croquetas del mercado. Reportan que sus mascotas no pueden masticar el alimento y lo rechazan.",gap:"No existe croqueta para razas pequeñas en el segmento económico. Los cambios de formato sorpresivos generan rechazo masivo y switching.",opportunity:"SKU segmentado por talla de perro con croqueta claramente diferenciada y fórmula consistente.",brands:[["Dog Chow",98],["Ringo",20],["Chunky",3],["Nutre Can",2]],evidence:125,fase3:9,comments:[{brand:"Dog Chow",likes:0,text:"Hola, mi perro solo come este alimento porque ninguno le gustó y le hacen daño. Ahora no quiere comer, el nuevo no le gustó y es de pepitas más grandes las cuales se le dificultan para comerlas."},{brand:"Dog Chow",likes:2,text:"Muy buenas, cambiaron la versión del alimento y mi perro de raza pequeña no quiere comer hace una semana."}]},
  {id:"d-clean",title:"Clean label / ingredientes transparentes",category:"producto",signal:"Los veterinarios están creando listas negras públicas de marcas con maíz como primer ingrediente. La conversación sobre ingredientes ya no es de nicho — es mainstream entre dueños informados.",gap:"Ninguna marca económica ofrece transparencia de ingredientes. El movimiento de alimentación natural crece como alternativa al concentrado.",opportunity:"Comunicar ingredientes reales, sin colorantes, proteína animal como primer ingrediente. Empaque con tabla de ingredientes legible y verificable.",brands:[["Dog Chow",14],["Ringo",8],["Nutre Can",1],["Nutriss",1]],evidence:24,fase3:45,comments:[{brand:"Dog Chow",likes:6,text:"Ay Isa no le des ese veneno que lo estás matando lentamente. El día que lo tengas que llevar a dormir porque el cáncer te lo mató, te vas a odiar."},{brand:"Dog Chow",likes:1,text:"Trigo integral molido, harina de trigo, maíz amarillo, fibra de soja y la cereza HARINA DE SUBPRODUCTOS DE POLLO. Sigan leyendo y por ningún lado tiene ni pollo ni leche."}]},
  {id:"d-raza",title:"Necesidad por raza y etapa de vida",category:"producto",signal:"Los dueños preguntan qué darle a su cachorro según raza y edad. La respuesta no existe en ningún empaque ni en ninguna comunicación de marca. Cada pregunta sin respuesta es un cliente que el veterinario redirige a premium.",gap:"Gap de información sobre qué producto usar según raza, edad y peso. Las tablas del empaque no resuelven la duda.",opportunity:"Líneas especializadas por etapa de vida y comunicación clara por raza. Calculadora de porciones con QR en empaque.",brands:[["Dog Chow",77],["Ringo",20],["Chunky",3],["Dogourmet",3]],evidence:106,fase3:0,comments:[{brand:"Dog Chow",likes:2,text:"Hola, quiero saber si pueden encontrar Dog Chow para cachorros de raza grande."},{brand:"Dog Chow",likes:0,text:"Para un perro beagle de tres años, dos porciones de Dog Chow son suficientes?"}]},
  {id:"d-contaminacion",title:"Contaminación y respuesta de crisis",category:"producto",signal:"Los consumidores reportan gusanos, producto vencido y cambios de calidad. Los reportes son públicos y virales — un solo caso genera cadena de desconfianza en toda la categoría, no solo en la marca afectada.",gap:"Ninguna marca tiene protocolo de respuesta pública en menos de 48 horas. La marca recoge la evidencia rápido pero tarda en responder al consumidor.",opportunity:"Empaque con indicador de frescura, sello verificable, y protocolo de respuesta en redes en menos de 24 horas como diferenciador.",brands:[["Dog Chow",15],["Ringo",2],["Chunky",1]],evidence:18,fase3:17,comments:[{brand:"Dog Chow",likes:7,text:"Es la segunda vez que me salen gusanos y animales en la comida de mi mascota. Pensé que era por el sitio pero este lo compré en Jumbo pensando que saldría mejor."},{brand:"Dog Chow",likes:4,text:"Ojo con el alimento lleno de gusanos. Efectivos y ágiles para recoger el producto podrido pero tardan 15 días en dar respuesta."}]},
  {id:"d-empaque-contamina",title:"El bulto de 22kg se contamina en la casa — no en la fábrica",category:"producto",signal:"La mayoría de quejas de gusanos y mal olor no son problemas de manufactura — son de almacenamiento casero. El empaque no es resellable, el consumidor lo abre, lo deja expuesto semanas, y el alimento se degrada. El último kilo del bulto huele diferente al primero.",gap:"Ningún empaque del segmento económico es resellable. El consumidor guarda el alimento en baldes, bolsas plásticas o lo deja abierto. La marca diseña para la fábrica, no para la cocina del consumidor.",opportunity:"Empaque resellable o porciones selladas individuales dentro del bulto. Resolver la contaminación en casa elimina la queja más viral de toda la categoría.",brands:[["Dog Chow",15],["Ringo",3],["Chunky",2]],evidence:20,fase3:8,comments:[{brand:"Dog Chow",likes:7,text:"Es la segunda vez que me salen gusanos. Pensé que era por el sitio pero este lo compré en Jumbo pensando que saldría mejor."},{brand:"Dog Chow",likes:3,text:"El alimento está con muy mal olor, se siente cuando ya está puesto en el plato del perro."}]},
  {id:"d-sin-prueba",title:"El dueño tiene que apostar $50K para descubrir si el perro lo acepta",category:"producto",signal:"No existe formato de prueba. Para probar una marca nueva, el dueño tiene que comprar un bulto completo. Si el perro lo rechaza, pierde $50K. Esa barrera de entrada protege a Dog Chow: el consumidor no se arriesga a cambiar porque el costo del error es un bulto entero.",gap:"Ninguna marca ofrece formato de prueba o muestra. El consumidor nuevo tiene que apostar su presupuesto mensual de alimento en una marca que su perro puede rechazar en la primera comida.",opportunity:"Formato de prueba (500g–1kg) a precio accesible. Eliminar la barrera de entrada. El consumidor que prueba y su perro acepta se convierte en cliente recurrente sin riesgo.",brands:[["Dog Chow",0],["Ringo",0],["Donkan",0]],evidence:14,fase3:6,comments:[{brand:"Dog Chow",likes:2,text:"Me siento en la obligación de comprarle Pro Plan pero me da miedo que no lo acepte y pierda la plata."},{brand:"Usuario",likes:1,text:"Alguien ha probado Nutre Can? No quiero comprar el bulto grande si al perro no le va a gustar."}]},
  {id:"d-snack-funcional",title:"Los premios son el segundo gasto diario — y solo hay golosinas o premium",category:"producto",signal:"Los dueños dan premios/snacks a diario como parte del vínculo con el perro. Es un gasto constante y emocional. Pero el mercado solo tiene golosinas baratas sin beneficio o snacks funcionales premium (dental, articulaciones) a $15K+.",gap:"No hay snack funcional económico. El dueño que quiere dental accesible o soporte articular tiene que pagar precio premium. Los snacks baratos son calorías vacías.",opportunity:"Línea de snacks funcionales Donkan: dental, articulaciones, digestión. Precio accesible. Capturar el gasto diario que ya existe con beneficio real.",brands:[["Dog Chow",6],["Ringo",2]],evidence:8,fase3:11,comments:[{brand:"Dog Chow",likes:0,text:"Mi perro ama los premios de Purina pero están carísimos. ¿Alguna alternativa más económica?"},{brand:"Usuario",likes:1,text:"¿Alguien conoce premios buenos para la dentadura del perro que no cuesten un ojo de la cara?"}]},
  {id:"d-intuicion",title:"El dueño alimenta por intuición — la tabla del empaque no funciona",category:"producto",signal:"Los consumidores preguntan constantemente cuánto darle a su perro. Las tablas del empaque existen pero nadie las entiende o las usa. El dueño decide la porción 'a ojo' y después se preocupa de si le da mucho o poco.",gap:"La comunicación de porciones en empaque es genérica e ilegible. No dice 'tu beagle de 3 años necesita X gramos.' Dice rangos amplios que no ayudan. El consumidor termina en redes sociales preguntando lo básico.",opportunity:"Tabla de porciones visual por raza + peso en empaque frontal. QR a calculadora personalizada. Convertir la pregunta más frecuente en diferenciador de producto.",brands:[["Dog Chow",31],["Ringo",8],["Chunky",2]],evidence:41,fase3:0,comments:[{brand:"Dog Chow",likes:0,text:"Para un perro beagle de tres años, dos porciones de Dog Chow son suficientes?"},{brand:"Dog Chow",likes:1,text:"Tengo un husky siberiano de 2 meses y medio y le doy Dog Chow cachorros. Quisiera saber la cantidad exacta en cada comida."}]},
];

export const catOpportunities: InnovationOpportunity[] = [
  {id:"c-indoor",title:"El gato indoor tiene 3 problemas que nadie resuelve juntos",category:"producto",signal:"Bolas de pelo, digestión sensible e hidratación insuficiente son problemas interconectados del gato indoor. Los dueños compran soluciones por separado o no encuentran ninguna en el segmento accesible.",gap:"No existe fórmula 'indoor' en el segmento económico que aborde los 3 problemas simultáneamente.",opportunity:"Línea DonKat Indoor: fórmula integral con control de bolas de pelo, soporte digestivo y promoción de hidratación.",brands:[["Cat Chow",51],["Mirringo",6],["Chunky Gatos",1]],evidence:66,fase3:3,comments:[{brand:"Cat Chow",likes:6,text:"He oído que Purina Cat Chow tiene una línea que sirve para controlar el pelo que los gatos ingieren al lamerse, es decir que este producto hace que ellos expulsen el pelo."},{brand:"Chunky Gatos",likes:0,text:"Me pueden decir cuál sabor de Chunky no trae esas bolas gigantes? Mis gatas las odian y terminan la mitad de la comida ahí, aislada."}]},
  {id:"c-sachets",title:"Los dueños ya mezclan húmedo + seco sin que nadie les venda el complemento",category:"producto",signal:"Los dueños de gatos combinan comida húmeda con seca por instinto: le ponen un poquito de lata encima del concentrado para que coma mejor. No lo hacen por nutrición — lo hacen porque el gato rechaza el seco solo. Están comprando sachets premium como 'truco' para que el gato acepte el económico.",gap:"No hay sachet o topper accesible diseñado para complementar el seco. Las latas y pouches que existen son premium y se venden como alimento completo, no como complemento.",opportunity:"Sachet/topper económico diseñado para mezclar: porción pequeña, sabor intenso, precio accesible. No compite con el seco — lo hace comestible. El dueño ya paga por esto, solo que le cobran precio premium.",brands:[["Cat Chow",9],["Mirringo",2],["Chunky Gatos",1]],evidence:12,fase3:8,comments:[{brand:"Cat Chow",likes:2,text:"Mi bb solo come Purina pero la verdad se ha subido mucho de precio, las latas a más de $4.300 en almacenes de cadena."},{brand:"Cat Chow",likes:1,text:"Mi gatico le gusta mucho el Cat Chow, traté de darle el ProPlan para mejorar su alimentación pero no lo toleró."}]},
  {id:"c-sobrepeso",title:"Control de peso post-esterilización: el problema que sigue al trigger",category:"producto",signal:"Después de la esterilización, el gato sube de peso. Los dueños lo reportan como el problema más visible y urgente post-cirugía. Cat Chow tiene línea 'peso saludable' pero los dueños no la encuentran o no la asocian con esterilización.",gap:"No hay línea económica que conecte esterilización → control de peso como secuencia lógica. El dueño busca 'esterilizado' y luego busca 'peso' como si fueran cosas distintas.",opportunity:"Sub-línea Esterilizado + Control de Peso como producto único. Resolver los dos momentos con una sola decisión de compra.",brands:[["Cat Chow",18],["Mirringo",1],["Chunky Gatos",0]],evidence:19,fase3:4,comments:[{brand:"Cat Chow",likes:4,text:"Tengo una gata siamés esterilizada de más de un año y gracias a este producto en tres meses perdió el sobrepeso, se volvió más activa."},{brand:"Cat Chow",likes:0,text:"Desde que esterilicé a mi gata se engordó mucho. Necesito un alimento que la ayude a bajar de peso pero que sea accesible."}]},
  {id:"c-hidratacion",title:"Hidratación y alimento húmedo",category:"producto",signal:"La comida húmeda pasó de ser lujo a necesidad médica. Los veterinarios la recomiendan activamente para hidratación, problemas urinarios y gatos en recuperación. La demanda es altísima y la oferta accesible es nula.",gap:"Pocas opciones de alimento húmedo accesible en Colombia. Las existentes son premium.",opportunity:"Línea de pouches/sobrecitos como complemento al seco. Posicionar como hidratación veterinaria, no como lujo.",brands:[["Cat Chow",16],["Mirringo",3],["Chunky Gatos",1]],evidence:20,fase3:31,comments:[{brand:"Cat Chow",likes:2,text:"Mi bb solo come Purina pero la verdad se ha subido mucho de precio, las latas a más de $4.300 en almacenes de cadena."},{brand:"Cat Chow",likes:1,text:"Mi gatico le gusta mucho el Cat Chow, traté de darle el ProPlan para mejorar su alimentación pero no lo toleró."}]},
  {id:"c-etapas",title:"Etapas de vida: esterilización como momento cero",category:"producto",signal:"La esterilización es el único momento donde el dueño busca activamente una marca nueva. Quien capture ese momento captura al cliente por años. Cat Chow domina por defecto porque nadie más ofrece línea específica.",gap:"No hay línea visible para gatos esterilizados en segmento económico fuera de Cat Chow.",opportunity:"Línea Esterilizados desde el lanzamiento. La esterilización es el trigger más fuerte de cambio de marca.",brands:[["Cat Chow",24],["Mirringo",1]],evidence:25,fase3:7,comments:[{brand:"Cat Chow",likes:4,text:"Tengo una gata siamés esterilizada de más de un año y gracias a este producto en tres meses perdió el sobrepeso, se volvió más activa y lo mejor es que el olor de sus deposiciones disminuyó."},{brand:"Cat Chow",likes:0,text:"Deseo cambiarle a mi gatica recién esterilizada el alimento pero necesito saber si este cumple con todos los nutrientes que necesita."}]},
  {id:"c-bolas",title:"Bolas de pelo y pelaje",category:"producto",signal:"Los gatos indoor sufren de bolas de pelo como problema crónico. Solo una marca ofrece solución específica en el mercado colombiano y domina el espacio sin competencia.",gap:"Mirringo no tiene línea específica. Chunky Gatos tampoco.",opportunity:"Línea con fórmula anti-bolas de pelo para gatos indoor y de pelo largo.",brands:[["Cat Chow",35],["Mirringo",5]],evidence:40,fase3:1,comments:[{brand:"Cat Chow",likes:2,text:"Yo le doy gatos hogareños control bolas de pelo... excelente."},{brand:"Cat Chow",likes:0,text:"Excelente alimento para mi Pancha. Pero quisiera saber si le puedo dar gatos hogareños control bolas de pelo, ella tiene 5 meses."}]},
  {id:"c-renal",title:"Salud urinaria y renal",category:"producto",signal:"Los problemas renales fuerzan a los dueños a pagar $180K por Hills k/d porque no hay alternativa accesible. Es el tema que genera más angustia emocional en los comentarios — dueños desesperados pidiendo opciones.",gap:"Solo marcas premium ofrecen fórmula urinaria. El salto de precio es de $40K a $180K sin escalón intermedio.",opportunity:"Fórmula con protección urinaria en segmento accesible. Capturar el momento de crisis antes de que el cliente se vaya a premium.",brands:[["Cat Chow",8],["Mirringo",2],["Chunky Gatos",1]],evidence:11,fase3:2,comments:[{brand:"Cat Chow",likes:0,text:"Mi gatito siempre ha comido Cat Chow porque solo quería comer de esa marca. Hace poco le diagnosticaron enfermedad renal crónica y ya no puede comer esas croquetas. Tengan cuidado."},{brand:"Cat Chow",likes:0,text:"Hola, mi gato tiene insuficiencia renal y le quitaron su Cat Chow. Me recomiendan alguno de estos nuevos?"}]},
  {id:"c-kitten",title:"Alimento kitten: la ventana para romper el lock-in",category:"producto",signal:"El lock-in biológico del gato se forma en la etapa kitten. El gato acepta alimentos nuevos solo en los primeros meses de vida. Después, rechaza todo lo que no sea su marca habitual. Quien capture al kitten, captura al gato por 15 años.",gap:"Cat Chow domina la etapa kitten por defecto. No hay alternativa económica visible que compita por la primera marca del gatito.",opportunity:"Línea DonKat Kitten con sabor y textura diferenciados. Muestras gratuitas en veterinarias y en puntos de adopción. Invertir en la etapa donde el gato aún acepta marcas nuevas.",brands:[["Cat Chow",14],["Mirringo",2],["Chunky Gatos",0]],evidence:16,fase3:4,comments:[{brand:"Cat Chow",likes:0,text:"Excelente alimento para mi Pancha. Pero quisiera saber si le puedo dar gatos hogareños control bolas de pelo, ella tiene 5 meses."},{brand:"Cat Chow",likes:2,text:"Tengo un gatico bebé de 2 meses y medio. Cuál Cat Chow le puedo dar?"}]},
  {id:"c-digestion",title:"Vómito y digestión felina",category:"producto",signal:"Los gatos vomitan al cambiar de alimento y los dueños interpretan el vómito como señal de mala calidad. El cambio de marca se convierte en trauma para el dueño — y refuerza el lock-in con la marca actual.",gap:"No hay alimento económico para gatos con digestión sensible. El dueño no sabe si el vómito es normal o problemático.",opportunity:"Fórmula Digestión Sensible como sub-línea especializada. Comunicación clara sobre transición de alimento.",brands:[["Cat Chow",5],["Mirringo",1]],evidence:6,fase3:3,comments:[{brand:"Cat Chow",likes:7,text:"Mi Shaddy solo come Cat Chow vida sana. Tiene 9 años. Será hora de pasarla a adultos porque veo que a veces vomita y eso no le pasaba antes. Está desparasitada, vacunas al día."},{brand:"Mirringo",likes:1,text:"Es la peor comida para los gatos. Les produce vómito."}]},
  {id:"c-contaminacion",title:"Contaminación y calidad",category:"producto",signal:"Los reportes de productos contaminados son públicos y virales. Generan desconfianza en toda la categoría felina, no solo en la marca afectada.",gap:"Ninguna marca felina económica comunica garantía de calidad ni tiene protocolo de respuesta visible.",opportunity:"Empaque con sello de calidad verificable y protocolo de respuesta pública.",brands:[["Cat Chow",2],["Chunky Gatos",2],["Mirringo",1]],evidence:5,fase3:29,comments:[{brand:"Cat Chow",likes:2,text:"Cat Chow es una Purina que mata a los animalitos. Compré un paquete para mi gatita, lo destapé y estaba lleno de moho."},{brand:"Cat Chow",likes:1,text:"El día sábado compramos una bolsa de Delimix en el Éxito de Floresta en Bogotá. La acabamos de destapar y el olor es inmundo."}]},
  {id:"c-clean",title:"Clean label e ingredientes transparentes",category:"producto",signal:"Los consumidores cuestionan la proteína vegetal y los colorantes. Los veterinarios incluyen Cat Chow en listas negras de marcas que nunca darían a sus mascotas por el maíz como primer ingrediente.",gap:"El segmento económico felino no tiene opciones clean-label.",opportunity:"Transparencia de ingredientes y proteína animal como primer ingrediente. Diferenciador inmediato.",brands:[["Cat Chow",2],["Mirringo",1],["Chunky Gatos",1]],evidence:4,fase3:31,comments:[{brand:"Cat Chow",likes:34,text:"La esterilización estoy de acuerdo. Pero esa marca en España no ayuda nada, es de la peor calidad que hay."},{brand:"Cat Chow",likes:0,text:"Puro veneno para gatos. Yo a mi gato no le doy pepas. Le doy pollito desmenuzado con verduras y pescado."}]},
  {id:"c-textura",title:"Para el gato la textura pesa más que el sabor — y nadie lo trabaja",category:"producto",signal:"Los gatos rechazan alimentos por textura antes de probar el sabor. Croquetas grandes, duras o con forma irregular son rechazadas. Los dueños reportan que el gato 'juega' con la croqueta pero no la come. La forma y tamaño de la croqueta determina la aceptación.",gap:"Todas las marcas económicas tienen croquetas genéricas de tamaño y forma estándar. Nadie diferencia la textura como atributo de producto para gatos.",opportunity:"Croqueta diseñada para el paladar felino: más pequeña, más blanda, forma que el gato pueda masticar cómodamente. Ganar la prueba en el plato.",brands:[["Cat Chow",7],["Chunky Gatos",3],["Mirringo",1]],evidence:11,fase3:2,comments:[{brand:"Chunky Gatos",likes:0,text:"Me pueden decir cuál sabor de Chunky no trae esas bolas gigantes? Mis gatas las odian y terminan la mitad de la comida ahí, aislada."},{brand:"Cat Chow",likes:0,text:"Mi gata no quiere comer las croquetas nuevas, están más duras que las anteriores."}]},
  {id:"c-precio-tracking",title:"El consumidor rastrea el precio del bulto mes a mes — y publica la inflación",category:"producto",signal:"Los dueños de gatos publican el precio exacto del bulto de Cat Chow: '$60K hace un año, $80K hoy.' No es solo queja — es tracking público de inflación. El consumidor sabe exactamente cuánto ha subido y lo documenta para otros.",gap:"Cat Chow sube precios porque no tiene competencia accesible. Cada subida de precio crea un consumidor más dispuesto a cambiar — pero no hay a dónde ir.",opportunity:"Entrar con precio 20-30% menor que Cat Chow y COMUNICAR la diferencia de precio directamente. El consumidor ya hizo la comparación — solo necesita la alternativa.",brands:[["Cat Chow",26],["Mirringo",3],["Chunky Gatos",1]],evidence:30,fase3:4,comments:[{brand:"Cat Chow",likes:5,text:"Si está demasiado caro, el bulto de Cat Chow lo compré a $80.000 y si sigue subiendo ya no habrá bolsillo que aguante."},{brand:"Cat Chow",likes:6,text:"A mi gatica solo le gusta esa marca, las otras le da vómito. Me va a dejar en quiebra porque es la más cara."}]},
  {id:"c-multi-gato",title:"Los hogares multi-gato compran volumen pero cada gato necesita algo distinto",category:"producto",signal:"Los hogares con 2-4 gatos compran el mismo alimento para todos, pero cada gato tiene necesidades distintas: uno esterilizado, otro con bolas de pelo, otro kitten. El dueño no puede comprar 3 bolsas distintas.",gap:"No hay fórmula 'all stages' que funcione para gatos de diferentes edades y condiciones en el mismo hogar. El dueño elige la del gato 'más difícil' y los demás comen lo mismo.",opportunity:"Fórmula multi-gato: una croqueta que cubra esterilizado + adulto + control pelo. El hogar multi-gato es el cliente más cautivo si le resuelves el dilema de una sola compra.",brands:[["Cat Chow",11],["Mirringo",2]],evidence:13,fase3:3,comments:[{brand:"Cat Chow",likes:0,text:"Tengo 3 gatos, uno esterilizado, una de 5 meses y otro de 2 años. Cuál Cat Chow les puedo dar a los tres?"},{brand:"Cat Chow",likes:1,text:"Le doy Cat Chow vida sana a los dos pero la gatita esterilizada necesita otra cosa y no puedo comprar dos bolsas diferentes."}]},
];

export const dogIdeal: IdealItem[] = [
  {n:"01",title:"Primer ingrediente: proteína animal",desc:"No maíz ni harina de subproducto. Comunicar en empaque frontal.",src:"Veterinarios crean listas negras de marcas con maíz como primer ingrediente"},
  {n:"02",title:"Sin colorantes artificiales",desc:"Croqueta color natural. Diferenciador inmediato vs toda la competencia.",src:"Movimiento anti-concentrado creciente entre consumidores informados"},
  {n:"03",title:"Croqueta calibrada por talla",desc:"Mini (menos de 10kg), mediana, grande. Formato consistente sin cambios sorpresa.",src:"Quejas masivas de dueños de razas pequeñas por croquetas grandes"},
  {n:"04",title:"Fórmula estable garantizada",desc:"Si tu perro lo come hoy, lo va a comer mañana. Claim que nadie usa.",src:"Patrón de switching post-cambio de fórmula en la competencia"},
  {n:"05",title:"QR con calculadora + WhatsApp vet",desc:"Escanea el empaque: porciones por raza/peso + línea de consulta veterinaria.",src:"Preguntas de alimentación sin respuesta en comentarios de todas las marcas"},
  {n:"06",title:"Sello de frescura visible",desc:"Indicador en empaque que muestra si el producto está fresco.",src:"Reportes de contaminación con respuesta lenta en competidores"},
];

export const catIdeal: IdealItem[] = [
  {n:"01",title:"Pouches como complemento de salud",desc:"Sobrecitos húmedos posicionados como hidratación veterinaria, no como lujo.",src:"Demanda altísima de alimento húmedo confirmada con engagement masivo"},
  {n:"02",title:"Línea Esterilizados desde el lanzamiento",desc:"El trigger #1 de búsqueda. Cat Chow captura por defecto. Capturar este momento.",src:"La esterilización es el único evento que dispara búsqueda activa de marca nueva"},
  {n:"03",title:"Proteína animal como primer ingrediente",desc:"Clean-label felino. Comunicar transparencia en empaque frontal.",src:"Veterinarios incluyen Cat Chow en listas negras por maíz y colorantes"},
  {n:"04",title:"Control urinario accesible",desc:"Fórmula con protección renal a precio accesible, no $180K como Hills.",src:"Dueños desesperados pidiendo opciones accesibles para gatos con problemas renales"},
  {n:"05",title:"Fórmula anti-bolas de pelo",desc:"Función específica para gatos indoor/pelo largo. Espacio dominado por una sola marca.",src:"Menciones consistentes de bolas de pelo como problema crónico sin solución accesible"},
  {n:"06",title:"Palatabilidad certificada",desc:"Aprobado por gatos exigentes. El gato elige — el dueño paga lo que el gato acepte.",src:"Lock-in biológico confirmado: gatos rechazan alternativas una vez acostumbrados"},
];

export const dogBrandChart: BrandChartData = {
  dimensions:["Olor/calidad","Granel/formato","Consistencia","Mezcla casera","Croqueta","Clean label","Raza/edad","Contaminación","Empaque","Sin prueba","Snacks","Porciones"],
  brands:["Dog Chow","Ringo","Chunky","Dogourmet"],
  colors:["#D4574E","#C77D32","#3B7DD8","#6C4F9E"],
  data:[[23,8,4,0],[42,15,8,0],[116,12,5,0],[19,5,3,0],[98,20,3,0],[14,8,0,0],[77,20,3,3],[15,2,1,0],[15,3,2,0],[0,0,0,0],[6,2,0,0],[31,8,2,0]],
};

export const catBrandChart: BrandChartData = {
  dimensions:["Indoor","Sachets","Sobrepeso","Hidratación","Esterilización","Bolas pelo","Renal","Kitten","Digestión","Contaminación","Clean label","Textura","Precio","Multi-gato"],
  brands:["Cat Chow","Mirringo","Chunky Gatos"],
  colors:["#D4574E","#C77D32","#3B7DD8"],
  data:[[51,6,1],[9,2,1],[18,1,0],[16,3,1],[24,1,0],[35,5,0],[8,2,1],[14,2,0],[5,1,0],[2,1,2],[2,1,1],[7,1,3],[26,3,1],[11,2,0]],
};
